### ISSUE TITLE
Class Codeception\Extension\Phantoman not defined

### ISSUE THREAD

**Issue by mabasic** [site5/phantoman#11]
```
 Class `Codeception\Extension\Phantoman` is not defined. Autoload it or include into '_bootstrap.php' file of 'tests' directory
```

Is there an extra step I need to do ?

**Comment by Laykou** [comment]
Module.init event has been just added to the codeception #1370 and it makes this issue possible to solve. :)

**Comment by grantlucas** [comment]
@Laykou Awesome. I'll look at getting this set up soon. :smile:
