### ISSUE TITLE
Don't fire phantomjs on codecept build

### ISSUE THREAD

**Issue by burdiyan** [site5/phantoman#22]
It seems like the script is trying to fire up phantomjs while doing `codecept build` which looks like an issue.

**Comment by grantlucas** [comment]
Thanks for the report! I *think* this issue will be addressed by #3 where I'll need to set it up so that PhantomJS only starts/stops for the suites it's enabled for. I'll add a note to that issue to ensure that `codecept build` is addressed as well.
