### ISSUE TITLE
Stop (and restart?) PhantomJS before updating it

### ISSUE THREAD

**Issue by igorsantos07** [site5/phantoman#23]
> *This issue happened because of #20, but as the binary is there, it could as well be executed without relation to Codeception, thus...*

If you have PhantomJS running in background and you try to update any composer package, the install command will run and fail with a message stating the `phantomjs` binary is being used.

Would be nice if:

* the binary was stopped before the update procedure
    - not sure if it would be possible to start the binary again with the same settings (maybe getting the command that started it? That's viewable on `ps aux`)
* OR the script noticed it was running and gave a better warning than an exception (not sure if this makes sense as well)

**Comment by grantlucas** [comment]
I'm hoping this will all be resolved when #20 is resolved though I haven't had a chance to dig into it more yet. Hoping to get to it soon.

Does this scenario happen often for you?

**Comment by igorsantos07** [comment]
Given the confusion over the other issue, I'm not sure where should this be fixed.
I guess that, since the binary "owner" is PhantomJS Installer, they should stop the binary before installing a new version?

**Comment by grantlucas** [comment]
Yeah, it's a bit of both. Phantoman needs to ensure it's stopped properly for sure, and it wouldn't hurt for PhantomJS installer to check if it's running before trying to install.

**Comment by igorsantos07** [comment]
Yeah :)
Gonna transfer this over to the installer as well. Sorry again! :see_no_evil:

**Comment by grantlucas** [comment]
Sounds good. Closing this issue for now :smile:
