### ISSUE TITLE
Do not try to re-install same PhantomJS version

### ISSUE THREAD

**Issue by igorsantos07** [site5/phantoman#24]
I've noticed that, after the first install, the scripts try to install again the same PhantomJS binary every time we mess around with Composer. Would be better if it noticed there was no need to update anything, and skip that procedure.

**Comment by grantlucas** [comment]
Hi there @igorsantos07. Phantoman doesn't take care of the actual installation of PhantomJS and instead relies on it being present already or installed with [PhantomJS Installer](https://github.com/jakoch/phantomjs-installer). If you're using the PhantomJS installer package, it has a `post-update-cmd` which re-runs the installation process to ensure the latest version is installed correctly. From what I can see, this is the same installation process as when first installed. It doesn't know if it's installing a new version or not.

I agree that it might be nice if it knew not to "install" when there's nothing to update. If you have some time, I'd recommend proposing that on their repo :smiley: 

Thanks!

**Comment by igorsantos07** [comment]
Whoops. Sorry man! 
There was so many phantom/selenium packages installations those days that I opened the issue in the wrong project! Hahaha

**Comment by grantlucas** [comment]
Ha no problem :smile:

**Comment by igorsantos07** [comment]
There's it: https://github.com/jakoch/phantomjs-installer/issues/17
