### ISSUE TITLE
Start and stop PhantomJS only for specific suites

### ISSUE THREAD

**Issue by grantlucas** [site5/phantoman#3]
In most cases we only want to start/stop PhantomJS for acceptance tests. It'd be better to use Codeception events to do this instead of `__construct` and `__destruct`.

At the moment, there are no events early enough to start PhantomJS before the WebDriver module is initialized. A [request for a new event before initialization](https://github.com/Codeception/Codeception/issues/1370) has been made.

- [ ] Ensure PhantomJS only starts for the suites it's enabled for
- [ ] Ensure PhantomJS doesn't run on `codecept build` (#22)

**Comment by grantlucas** [comment]
[Codeception Issue 1370](https://github.com/Codeception/Codeception/issues/1370) has now added a `module.init` event which would be fired in time to determine which suite is being run before setting up an extension.

**Comment by igorsantos07** [comment]
I've thought about the same thing. My approach was another: ask if it's possible to enable extensions selectively for each suite, and by environment. See Codeception/codeception#2031

**Comment by grantlucas** [comment]
Hi @igorsantos07, I know you'll get the email response but I wanted to log it here as well for my own memory :smile: 

I [left a comment on the Codeception issue you posted](https://github.com/Codeception/Codeception/issues/2031#issuecomment-110557829) that I *think* will handle the environment issues.

**Comment by grantlucas** [comment]
Phantoman now has a base requirement of Codeception 2.1.X so this issue is good to be worked on. I'll hopefully get to this soon

**Comment by acuthbert** [comment]
Hi @grantlucas I've posted a PR #40 for a suggested solution. It's maybe not what's discussed here but works well for me in the meantime.

**Comment by disconnekt** [comment]
@grantlucas Hi! Will you accept this PR soon?

**Comment by grantlucas** [comment]
:fearful: Sorry about that! This PR completely slipped my mind. I'll get it reviewed and tested this morning.

**Comment by grantlucas** [comment]
Alright, after taking a look, here's the current state of affairs with @acuthbert 's PR #40 with regard to Phantoman only starting for specific suites.

## Scenario

Let's say I have three suites, `unit`, `acceptance`, and `api`, and PhantomJS is needed for acceptance and api suites so I enable it with the following in `codeception.yml`.

```yaml
extensions:
    enabled:
        - Codeception\Extension\Phantoman
    config:
        Codeception\Extension\Phantoman:
            suites: ['acceptance', 'api']
```

## Behaviour with PR #40

1. Running JUST unit tests: **PhantomJS doesn't start**
  - :dancer: Perfect. That's what we want
- Running JUST acceptance *or* api suites: **PhantomJS starts**
  - :dancers: Great again! That's what we want
  - One change to the PR will be to shut down on `__destruct` instead of `after.suite` since it would try to kill the proc after each suite instead of leaving it running
- Running **all** suites: **PhantomJS starts and stays running for all suites**
  - Hmm, so here PhantomJS is running for the unit tests suite which isn't really what we wanted I think

-------------------

So with all that in mind, what say you all? Would how this works address the issues of those who need Phantoman to start only for specific suites?

**Comment by grantlucas** [comment]
From what I can tell, due to Webdriver module needing PhantomJS on initialization, there's no way to start & stop PhantomJS around every suite that needs it and ignore the others.

Ideally I could tie into before and after suite events to start and stop it but that's not possible due to how WebDriver works. :cry:

**Comment by disconnekt** [comment]
In my cases I need to start only one a tests suit for my CI. And Unit tests (for example) have overhead on the test server because they run PhantomJs. I would to have this feature in your package. :cry:

**Comment by grantlucas** [comment]
Sounds good @disconnekt. Thanks for the input!

**Comment by grantlucas** [comment]
Update for everyone on this issue. A new PR has been set up (#43) which should address the starting of PhantomJS for only specific suites. This shouldn't introduce any backwards compatibility issues so a new release will be made like normal.

**Comment by grantlucas** [comment]
Hi everyone. PR #43 has now been merged and thus hopefully resolving this issue. 😄

**Comment by grantlucas** [comment]
New tag btw is `v1.1.0`
