### ISSUE TITLE
Enable overriding phantoman settings with codeception environments

### ISSUE THREAD

**Issue by fgerards** [site5/phantoman#39]
It seems that in latest codeception version,
a setting like:

extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\Phantoman
    config:
            Codeception\Extension\Phantoman:
                proxy: '<myproxy>'
                proxyType: 'http'

in an environment file doesnt alter the phantoman phantomjs call.
Setting the proxy in the codeception.yml works. 

Overriding module settings etc. in the same env-yml file works, too.
Dunno if this is really related to phantoman extension or a bug inside codeption though.

Thx 4 help !

**Comment by grantlucas** [comment]
Hi @fgerards. Just for some clarification, are you wanting to override certain Phantoman settings based on environment? Can you describe your setup a bit?

Thanks!

**Comment by grantlucas** [comment]
Going to close this issue due to inactivity. @fgerards Please re-open if this is still an issue.
