### ISSUE TITLE
Newest version not available for detected OS.

### ISSUE THREAD

**Issue by davidjeddy** [site5/phantoman#41]
CentOS release 6.7 (Final) x64
Logic does a good job of detecting the OS and the most recent stable release of phantomjs. However, there is no stable release at the current version for the OS detected.

```BASH
 [Composer\Downloader\TransportException]                                                                                                          
  The "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2" file could not be downloaded (HTTP/1.1 404 NOT FOUND)
```

...per https://bitbucket.org/ariya/phantomjs/downloads/

Solution: if the request returns anything other than status 200, tick down one version and try again but no go below the lowest supported version.

**Comment by grantlucas** [comment]
Hi there. I think you might need to post an issue in the [PhantomJS Installer package](https://github.com/jakoch/phantomjs-installer) repo since Phantoman doesn't do anything directly with PhantomJS other than use it.

**Comment by davidjeddy** [comment]
You are correct, my mistake. TY

**Comment by grantlucas** [comment]
No problem!
